# Find out more about tasks: http://docs.devo.ps/manual/tasks

id: build-laravel
name: Build Laravel app
type: task

targets:
  - laravel

vars:
  workdir: /var/www/laravel
  repo: https://github.com/scotch-io/laravel-angular-comment-app
  php_run_user: "{{ nodes.laravel.configuration.php.fpm.pool.user }}"

  laravel_db: laravel
  laravel_user: laravel
  laravel_pass: "{{ nodes.laravel.configuration.mysql.users.laravel.password }}"


steps:
  - run: devops git update
    options:
      repo: "{{ repo }}"
      dest: "{{ workdir }}"

  - run: devops scripts/build-laravel.sh

